<?php
$this->headLink()
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));

$this->headScript()
    ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('js/setup/vacancy/index.js'));

?>
<?php if ($this->messages) { ?>
    <script>
        document.messages = <?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.editLink = '<?= $this->url("vacancy", ["action" => "edit"]) ?>';
    document.deleteLink = '<?= $this->url("vacancy", ["action" => "delete"]) ?>';
    document.acl = <?php echo json_encode($acl); ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\Vacancy')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="margin-top-20">
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <?php if ($acl['ALLOW_ADD'] == 'Y'): ?>


                    <a href="<?= $this->url('vacancy', ['action' => 'add']) ?>" class="btn default btn-sm">
                        <i class="fa fa-plus-square icon-black"></i>
                        New
                    </a>

                    <a href="http://hr.neosoftware.com.np:8561/vacancy/vacancy.php" class="btn default btn-sm">
                        <i class="fa fa-plus-square icon-black"></i>
                        Vacancy Link
                    </a>


                    


                <?php endif; ?>
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;" id="export" class="hris-export-to-excel" hris-export-to-excel-target="vacancyTable">
                                <i class="fa fa-file-excel-o"></i> Export to Excel </a>
                        </li>
                        <li>
                            <a href="javascript:;" id="pdfExport">
                                <i class="fa fa-file-pdf-o"></i>
                                Export to PDF
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div id="vacancyTable">
        </div>
    </div>
</div>