<?php
$this->headLink()
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));

$this->headScript()
    ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('js/search.js'))
    ->appendFile($this->basePath('js/mustache.js'))
    ->appendFile($this->basePath('assets/global/plugins/jsPDF-master/dist/jspdf.debug.js'))
    ->appendFile($this->basePath('js/Payroll/payrollReport/letterToBank.js?1'));
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages = <?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.searchValues = <?php echo json_encode($searchValues); ?>;
    document.getFiscalYearMonthLink = '<?php echo $this->url('payrollReport', ['action' => 'getFiscalYearMonth']); ?>';
    document.pullLetterToBankDetail = '<?= $this->url("payrollReport", ["action" => "pullLetterToBankDetail"]) ?>';
    document.salaryType = <?php echo json_encode($salaryType); ?>;
    document.bankType = <?php echo json_encode($bankType); ?>;
    document.preference = <?php echo json_encode($preference) ?>;
    document.incomes = <?php echo json_encode($incomes); ?>;
    document.acl = <?php echo json_encode($acl); ?>;
    document.taxExcemptions = <?php echo json_encode($taxExcemptions); ?>;
    document.otherTax = <?php echo json_encode($otherTax); ?>;
    document.miscellaneous = <?php echo json_encode($miscellaneous); ?>;
    document.bMiscellaneou = <?php echo json_encode($bMiscellaneou); ?>;
    document.cMiscellaneou = <?php echo json_encode($cMiscellaneou); ?>;
    document.sumOfExemption = <?php echo json_encode($sumOfExemption); ?>;
    document.sumOfOtherTax = <?php echo json_encode($sumOfOtherTax); ?>;
    document.controlValues = <?php echo json_encode($controlValues); ?>;
</script>

<style>
    .table-condensed>thead>tr>th,
    .table-condensed>thead>tr>td,
    .table-condensed>tbody>tr>th,
    .table-condensed>tbody>tr>td,
    .table-condensed>tfoot>tr>th,
    .table-condensed>tfoot>tr>td {
        padding: 0px;
    }
</style>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\monthlyValue')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div>
    <div class="row">
        <div class="col-sm-12 ">
            <div class="portlet light bg-inverse">
                <div class="portlet-title">
                    <div class="caption">
                        <button id="display" class="btn btn-default btn-sm pull-right">
                            Display
                            <i class="fa fa-play"></i>
                        </button>
                        <!-- <i class="icon-paper-plane font-green-haze"></i>
                        <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
                    </div> -->
                    </div>
                    <div class="tools">
                        <!-- <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                        <a href="" class="fullscreen" data-original-title="" title=""> </a> -->
                    </div>
                    <div class="actions">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
                            <i class="fa fa-filter"></i> Filter
                        </button>
                        <div class="btn-group">
                            <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                                <i class="fa fa-copy"></i> Export
                                <i class="fa fa-angle-down "></i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li>
                                    <a href="javascript:;" id="excelExport">
                                        <i class="fa fa-file-excel-o"></i> Export to Excel </a>
                                </li>
                                <li>
                                    <a href="javascript:;" id="pdfExport">
                                        <i class="fa fa-file-pdf-o"></i> Export to PDF </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="portlet-body">

                    <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h3 class="modal-title" id="exampleModalLongTitle">Advance Filter</h3>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>

                                <div class="row margin-top-10">
                                    <div class="col-sm-6">
                                        <label>Year</label>
                                        <select id="fiscalYearId">
                                        </select>
                                    </div>
                                    <div class="col-sm-6">
                                        <label>Month</label>
                                        <select id="monthId">
                                        </select>
                                    </div>
                                </div>
                                <!-- <div class="col-sm-2">
                                        <label>Bank</label>
                                        <select class="form-control" name="bankType" id="bankTypeId" required>
                                        </select>
                                    </div> -->
                                <div class="row margin-top-10">
                                    <div class="col-sm-6">
                                        <label>Salary Type</label>
                                        <select class="form-control reset-field" name="salaryType" id="salaryTypeId">
                                        </select>
                                    </div>
                                    <div class="col-sm-6">
                                        <label>Pay Head</label>
                                        <select class="form-control" name="payHead" id="payHead">
                                            <option value="NS">Net Salary</option>
                                            <option value="SSF 31">SSF</option>
                                            <option value="PF20">PF</option>
                                            <option value="GT33">Gratuity</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="row margin-top-10">
                                    <div class="col-sm-6" id='companyDiv'>
                                        <label>Company</label>
                                        <select class="form-control" name="company" id="companyId">
                                        </select>
                                    </div>
                                </div>
                                <!-- <div class="col-sm-2">
                                    <label>Group</label>
                                    <select class="form-control" name="groupId" id="groupId">
                                    </select>
                                </div> -->
                                <div class="modal-footer">
                                    <div class="col-sm-4 col-sm-offset-8">
                                        <button id="reset" class="btn default btn-sm pull-right">
                                            Reset
                                            <i class="fa fa-refresh"></i>
                                        </button>
                                        <button id="searchEmployeesBtn" class="btn btn-default btn-sm pull-right">
                                            Search
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row margin-top-10">
                        <!-- <div class="col-sm-2">
                            <label>Year</label>
                            <select id="fiscalYearId">
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <label>Month</label>
                            <select id="monthId">
                            </select>
                        </div> -->
                        <div class="col-sm-3">
                            <label>Bank</label>
                            <select class="form-control" name="bankType" id="bankTypeId" required>
                            </select>
                        </div>
                        <!-- <div class="col-sm-2">
                            <label>Salary Type</label>
                            <select class="form-control reset-field" name="salaryType" id="salaryTypeId">
                            </select>
                        </div> -->
                        <!-- <div class="col-sm-2">
                            <label>Pay Head</label>
                            <select class="form-control" name="payHead" id="payHead">
                                <option value="NS">Net Salary</option>
                                <option value="SSF 31">SSF</option>
                                <option value="PF20">PF</option>
                                <option value="GT33">Gratuity</option>
                            </select>
                        </div> -->
                        <!-- <div class="col-sm-2" id='companyDiv'>
                            <label>Company</label>
                            <select class="form-control" name="company" id="companyId">
                            </select>
                        </div> -->
                        <!-- <div class="col-sm-2">
                            <label>Group</label>
                            <select class="form-control" name="groupId" id="groupId">
                            </select>
                        </div> -->
                    </div>

                    <!-- <div class="row margin-top-10">
                        <div class="col-sm-4 col-sm-offset-8">
                            <button id="reset" class="btn default btn-sm pull-right">
                                Reset
                                <i class="fa fa-refresh"></i>
                            </button>
                            <button id="searchEmployeesBtn" class="btn btn-default btn-sm pull-right">
                                Search
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div> -->


                </div>
            </div>

            <div class="portlet light bg-inverse">
                <!-- <div class="portlet-title">
                    <div class="tools">
                        <a href="" class="fullscreen" data-original-title="" title=""> </a>
                    </div>

                    <div class="actions">
                        <div class="btn-group">
                            <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                                <i class="fa fa-copy"></i> Tools
                                <i class="fa fa-angle-down "></i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li>
                                    <a href="javascript:;" id="excelExport">
                                        <i class="fa fa-file-excel-o"></i>
                                        Export to Excel
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:;" id="pdfExport">
                                        <i class="fa fa-file-pdf-o"></i>
                                        Export to PDF
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div> -->
                <div class="portlet-body">
                    <div id="table" style="padding:0%;">
                    </div>
                    <div id="kendoTable" style="padding:0%; display:none;">
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .portlet.light .portlet-body {
        padding-top: 0px !important;
    }

    .portlet {
        margin-bottom: 6px !important;
    }

    h4,
    .h4,
    h5,
    .h5,
    h6,
    .h6 {
        margin-top: 10px;
        margin-bottom: -14px;
    }

    .portlet>.portlet-body p {
        margin-top: -19px;
    }

</style>