<?php
//print"<pre>";print_r($employeesBirthday['TODAY']);exit;
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/bootstrap-datepicker/css/datepicker3.css'))
    ->appendStylesheet($this->basePath('assets/global/plugins/fullcalendar/fullcalendar.min.css'))
    ->appendStylesheet($this->basePath('css/dashboard.employee.css'));

$this->headScript()
    ->appendFile($this->basePath('assets/global/plugins/bootstrap-daterangepicker/moment.min.js'))
    ->appendFile($this->basePath('assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.js'))
    ->appendFile($this->basePath('assets/global/plugins/fullcalendar/fullcalendar.min.js'))
    ->appendFile($this->basePath('assets/admin/pages/scripts/components-pickers.js'))
    ->appendFile($this->basePath('assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js'))
    ->appendFile($this->basePath('assets/global/scripts/metronic.js'))
    ->appendFile($this->basePath('jquery_lazyload-master/jquery.lazyload.min.js'))
    ->appendFile($this->basePath('assets/admin/pages/scripts/index.js'))
    ->appendFile($this->basePath('js/nepali-calendar.js'))
    ->appendFile($this->basePath('js/nep.js'))
    ->appendFile($this->basePath('js/dashboard/employee-dashboard.js'));

$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/lobilist-master/dist/lobilist.min.css'));

$this->headScript()
    ->appendFile($this->basePath('assets/global/plugins/lobilist-master/dist/lobilist.min.js'))
    ->appendFile($this->basePath('js/dashboard/todo.js'));
?>

<script type="text/javascript">
    document.calendarUrl = '<?php echo $this->url('dashboard', ['action' => 'fetchEmployeeCalendarData']); ?>';
    document.calendarJsonFeedUrl = '<?php echo $this->url('dashboard', ['action' => 'fetchEmployeeCalendarJsonFeed']); ?>';
</script>
<script>
    document.todoAddUrl = '<?php echo $this->url('task', ['action' => 'add']); ?>';
    document.todoUpdateUrl = '<?php echo $this->url('task', ['action' => 'update']); ?>';
    document.todoDeleteUrl = '<?php echo $this->url('task', ['action' => 'delete']); ?>';
    document.todoTaskList = <?php echo json_encode($todoList); ?>;
    document.todoTaskUpdateStatus = '<?php echo $this->url('task', ['action' => 'updateStatus']); ?>';
    document.getEmpDashboardUrl = '<?php echo $this->url('dashboard', ['action' => 'fetchEmployeeDashBoardDetails']); ?>'
    document.changeCalendar = '<?php echo $this->url('dashboard', ['action' => 'changeCalendar']); ?>'
    document.calendarType = '<?php echo $calendarType ?>'
</script>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages = <?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<?php
$presentUrl = $this->url('myattendance', ['action' => 'index', 'id' => 1]);
$OnLeaveUrl = $this->url('myattendance', ['action' => 'index', 'id' => 2]);
$OnTrainingUrl = $this->url('myattendance', ['action' => 'index', 'id' => 3]);
$OnTravelUrl = $this->url('myattendance', ['action' => 'index', 'id' => 4]);
$wohUrl = $this->url('myattendance', ['action' => 'index', 'id' => 5]);
$lateInUrl = $this->url('myattendance', ['action' => 'index', 'id' => 6]);
$earlyOutUrl = $this->url('myattendance', ['action' => 'index', 'id' => 7]);
$missPunchUrl = $this->url('myattendance', ['action' => 'index', 'id' => 8]);
$performanceUrl = $this->url('myattendance', ['action' => 'index', 'id' => 9]);

?>
<style>
    /* Switch button style */
    .switch {
        position: relative;
        display: inline-block;
        width: 61px;
        height: 46px;
    }

    .switch input {
        opacity: 0;
        width: 0;
        height: 0;
    }

    .slider {
        position: absolute;
        cursor: pointer;
        top: -12px;
        left: 0;
        right: 0;
        bottom: 13px;
        background-color: #ccc;
        transition: 0.4s;
    }

    .slider:before {
        position: absolute;
        content: "";
        height: 13px;
        width: 15px;
        left: 4px;
        bottom: 4px;
        background-color: white;
        transition: 0.4s;
    }

    input:checked+.slider {
        background-color: #2196F3;
    }

    input:checked+.slider:before {
        transform: translateX(26px);
    }

    /* Rounded slider */
    .slider.round {
        border-radius: 34px;
    }

    .slider.round:before {
        border-radius: 50%;
    }
</style>

<div class="employeedashboard">
    <div class="emplyoee-dashboard col-md-12">
        <div class="row">
            <div class="employe-descbox">
                <div class="col-sm-2 col-md-1 profile_pic">
                    <img id="employeeImage" src="<?php print $this->basePath("img/nobody_m.original.jpg"); ?>">
                </div>
                <div class="col-sm-3 col-md-3 employee-details">

                    <h4 class="font-weight-bold" id="employeeFullName"></h4>
                    <span id="employeeOfficialEmail"></span><br>
                    <span id="employeeDesignationTitle"></span><br>
                    <span id="employeeServiceDate"></span><br>
                </div>
                <div class="col-md-5">
                    <div class="row detailsbox">
                        <a href="<?php echo $presentUrl ?>">
                            <div class="col-xs-6 col-sm-3 col-md-2 hexcustom">
                                <div class="employee_details-box hexagon-bg1">
                                    <span id="employeePresentDays">0</span>
                                    <div class="face1"></div>
                                    <div class="face2"></div>
                                    <div class="headtitle"><?php echo ($calendarType == 'N') ? 'उपस्थित' : 'Present' ?></div>
                                </div>
                            </div>
                        </a>

                        <a href="<?php echo $OnLeaveUrl ?>">
                            <div class="col-xs-6 col-sm-3 col-md-2 hexcustom">
                                <div class="employee_details-box hexagon-bg2">
                                    <span id="employeeLeaveDays">0</span>
                                    <div class="face1"></div>
                                    <div class="face2"></div>
                                    <div class="headtitle"><?php echo ($calendarType == 'N') ? 'बिदा' : 'On Leave' ?></div>
                                </div>
                            </div>
                        </a>

                        <a href="<?php echo $OnTrainingUrl ?>">
                            <div class="col-xs-6 col-sm-3 col-md-2 hexcustom">
                                <div class="employee_details-box hexagon-bg3">
                                    <span id="employeeTrainingDays">0</span>
                                    <div class="face1"></div>
                                    <div class="face2"></div>
                                    <div class="headtitle"><?php echo ($calendarType == 'N') ? 'प्रशिक्षण' : 'Training' ?></div>
                                </div>
                            </div>
                        </a>

                        <a href="<?php echo $OnTravelUrl ?>">
                            <div class="col-xs-6 col-sm-3 col-md-2 hexcustom">
                                <div class="employee_details-box hexagon-bg4">
                                    <span id="employeeTravelDays">0</span>
                                    <div class="face1"></div>
                                    <div class="face2"></div>
                                    <div class="headtitle"><?php echo ($calendarType == 'N') ? 'भ्रमणमा' : 'On Tour' ?></div>
                                </div>
                            </div>
                        </a>

                        <a href="<?php echo $wohUrl ?>">
                            <div class="col-xs-6 col-sm-3 col-md-2 hexcustom">
                                <div class="employee_details-box hexagon-bg5">
                                    <span id="employeeWOHDays">0</span>
                                    <div class="face1"></div>
                                    <div class="face2"></div>
                                    <div class="headtitle"><?php echo ($calendarType == 'N') ? 'घरबाट' : 'WOH' ?></div>
                                </div>
                            </div>
                        </a>
                        <?php 
// Extract the PERFORMANCE_PERCENTAGE value correctly
$performancePercentageValue = isset($performancePercentage[0]['PERFORMANCE_PERCENTAGE']) ? $performancePercentage[0]['PERFORMANCE_PERCENTAGE'] : 'N';

if ($performancePercentageValue == 'Y'): 
?>
    <!-- Performance Section -->
    <a href="<?php echo $performanceUrl ?>">
        <div class="col-xs-2 col-sm-2 col-md-2 hexcustom">
            <div class="employee_details-box hexagon-bg4">
                <span id="employeePerformanceDays">0</span>
                <div class="face1"></div>
                <div class="face2"></div>
                <div class="headtitle"><?php echo ($calendarType == 'N') ? 'Punctuality ' : 'Punctuality' ?></div>
            </div>
        </div>
    </a>
<?php endif; ?>
                    </div>
                </div>
                <div class="col-xs-12  col-sm-7 col-md-3">
                    <div class="col-hris row attendence-box">
                        <ul>
                            <a href="<?php echo $lateInUrl ?>">
                                <li class="col-xs-4 col-sm-4 col-md-4">
                                    <div class="hris efficiency efficiency-bg1">
                                        <span id="employeeLateInDays">0</span>
                                        <div><?php echo ($calendarType == 'N') ? 'ढिलो' : 'Late In' ?></div>
                                    </div>
                                </li>
                            </a>
                            <a href="<?php echo $earlyOutUrl ?>">
                                <li class="col-xs-4 col-sm-4 col-md-4">
                                    <div class="hris efficiency efficiency-bg2">
                                        <span id="employeeEarlyOutDays">0</span>
                                        <div><?php echo ($calendarType == 'N') ? 'चाँडै' : 'Early Out' ?></div>
                                    </div>
                                </li>
                            </a>
                            <a href="<?php echo $missPunchUrl ?>">
                                <li class="col-xs-4 col-sm-4 col-md-4">
                                    <div class="hris efficiency efficiency-bg3">
                                        <span id="employeeMissPunch">0</span>
                                        <div><?php echo ($calendarType == 'N') ? 'चुक्का गरिएको' : 'Missed Punch' ?></div>
                                    </div>
                                </li>
                            </a>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<!--news panel start-->
<?php if ($noticeType == 'M') : ?>
    <div class="row">
        <?php foreach ($employeeNews as $newsType) : ?>
            <div class="col-sm-6 col-md-3 col-lg-3">
                <div class="panel panel-green custompanel">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="hugo"> <?= $newsType['NEWS_TYPE_DESC']; ?> </div>
                            </div>
                        </div>
                    </div>
                    <!-- Slider News Goes Here -->
                    <div class="notification">
                        <ul class="list-group fixed-height panel-group">

                            <?php
                            foreach ($newsType['news'] as $newsData) {
                            ?>
                                <li class="list-group-item"> <a href="<?= $this->url('news-status', ['action' => 'view', 'id' => $newsData['NEWS_ID']]) ?>"><?= $newsData['NEWS_TITLE'] ?></a></li>
                            <?php
                            }
                            ?>
                        </ul>
                    </div>
                    <a href="<?= $this->url('news-status', ['action' => 'allNewsTypeList', 'id' => $newsType['NEWS_TYPE_ID']]); ?>">
                        <div class="panel-footer">
                            <span class="pull-left"> <?php echo ($calendarType == 'N') ? 'विवरण हेर्नुहोस्' : 'View Details' ?>
                            </span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>

                        </div>
                    </a>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<!--news panel end-->

<div class="row">
    <div class="col-md-12">
        <div class="portlet light calendar boxborder">
            <div class="portlet-title ">
                <div class="caption">
                    <i class="fa fa-calendar font-green-sharp"></i>
                    <span class="caption-subject font-green-sharp bold"><?php echo ($calendarType == 'N') ? 'पात्रो' : 'Calendar' ?>
                    </span>
                </div>
            </div>
            <div class="portlet-body">
                <div class="row" style="">
                    <div class="col-sm-3">
                        <select class="form-control" id="nc-year"></select>
                    </div>
                    <div class="col-sm-3">
                        <select class="form-control" id="nc-month"></select>
                    </div>
                    <div class="col-sm-3" style="display: none;">
                        <span id="calendar-label" class="mt-3">नेपाली</span>
                        <label class="switch">
                            <input type="checkbox" id="calendar-switch" <?php echo ($calendarType) == 'E' ? 'checked' : '' ?>>
                            <span class="slider round"></span>
                        </label>
                        <span id="calendar-label">English</span>
                    </div>
                </div>

                <div id="nepaliCalendar" class="nc-container">
                    <table id="nc-content" class="table table-bordered">

                        <?php if ($calendarType == 'N') : ?>
                            <tr>
                                <td class="nc-box">
                                    <div class="nc-header">आइतबार</div>
                                    <div id="nc-sunday"></div>
                                </td>
                                <td class="nc-box">
                                    <div class="nc-header">सोमबार</div>
                                    <div id="nc-monday"></div>
                                </td>
                                <td class="nc-box">
                                    <div class="nc-header">मङ्गलबार</div>
                                    <div id="nc-tuesday"></div>
                                </td>
                                <td class="nc-box">
                                    <div class="nc-header">बुधबार</div>
                                    <div id="nc-wednesday"></div>
                                </td>
                                <td class="nc-box">
                                    <div class="nc-header">बिहीबार</div>
                                    <div id="nc-thrusday"></div>
                                </td>
                                <td class="nc-box">
                                    <div class="nc-header">शुक्रबार</div>
                                    <div id="nc-friday"></div>
                                </td>
                                <td class="nc-box">
                                    <div class="nc-header">शनिबार</div>
                                    <div id="nc-saturday"></div>
                                </td>
                            </tr>
                        <?php else : ?>
                            <tr>
                                <td class="nc-box">
                                    <div class="nc-header">Sunday</div>
                                    <div id="nc-sunday"></div>
                                </td>
                                <td class="nc-box">
                                    <div class="nc-header">Monday</div>
                                    <div id="nc-monday"></div>
                                </td>
                                <td class="nc-box">
                                    <div class="nc-header">Tuesday</div>
                                    <div id="nc-tuesday"></div>
                                </td>
                                <td class="nc-box">
                                    <div class="nc-header">Wednesday</div>
                                    <div id="nc-wednesday"></div>
                                </td>
                                <td class="nc-box">
                                    <div class="nc-header">Thursday</div>
                                    <div id="nc-thrusday"></div>
                                </td>
                                <td class="nc-box">
                                    <div class="nc-header">Friday</div>
                                    <div id="nc-friday"></div>
                                </td>
                                <td class="nc-box">
                                    <div class="nc-header">Saturday</div>
                                    <div id="nc-saturday"></div>
                                </td>
                            </tr>

                        <?php endif; ?>
                    </table>
                </div>
                <div class="calendar-colorbox">
                    <ul>
                        <li>
                            <div class="color-box colorbox-color1"></div>
                            <span> <?php echo ($calendarType == 'N') ? 'छुट्टी' : 'Holiday' ?></span>
                        </li>
                        <li>
                            <div class="color-box colorbox-color2"></div>
                            <span> <?php echo ($calendarType == 'N') ? 'छोड' : 'Leave' ?></span>
                        </li>
                        <li>
                            <div class="color-box colorbox-color3"></div>
                            <span> <?php echo ($calendarType == 'N') ? 'प्रशिक्षण' : 'Training' ?></span>
                        </li>
                        <li>
                            <div class="color-box colorbox-color4"></div>
                            <span> <?php echo ($calendarType == 'N') ? 'भ्रमण' : 'Tour' ?></span>
                        </li>
                        <li>
                            <div class="color-box colorbox-color5"></div>
                            <span><?php echo ($calendarType == 'N') ? 'अनुपस्थित' : 'Absent' ?></span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <?php if ($noticeType == 'S') : ?>
            <div class="row">
                <div class="col-md-12">
                    <div class="profile-content">
                        <div class="row">
                            <div class="col-md-12 noticeboard">
                                <div class="portlet-body">
                                    <div class="portlet light boxborder">
                                        <div class="portlet-title tabbable-line">
                                            <div class="caption caption-md">
                                                <i class="fa fa-newspaper-o font-green-sharp" aria-hidden="true"></i>
                                                <span class="caption-subject font-green-sharp bold"><?php echo ($calendarType == 'N') ? 'सूचना पाटी' : 'Notice Board' ?></span>
                                            </div>
                                        </div>
                                        <div class="noticeboard-list row">
                                            <ul>
                                                <?php if (count($employeeNotice) > 0) : ?>
                                                    <?php foreach ($employeeNotice as $notice) : ?>
                                                        <li style="width:100%;">
                                                            <div class="calendardate-box col-xs-4 col-sm-2 col-md-2">
                                                                <span><?php print $notice['NEWS_DAY']; ?></span><br>
                                                                <?php print $notice['NEWS_MONTH_YEAR']; ?>
                                                            </div>
                                                            <div class="notice-details col-xs-8 col-sm-10 col-md-10">
                                                                <h5 class="title-color caption-subject  bold"><?php print $notice['NEWS_TITLE']; ?></h5>
                                                                <p><?php print $notice['NEWS_EDESC']; ?></p>
                                                            </div>
                                                        </li>
                                                    <?php endforeach; ?>
                                                <?php else : ?>
                                                    <li style="width:100%;">
                                                        <div class="calendardate-box col-xs-4 col-sm-2 col-md-2">
                                                            <span><?php print date('d'); ?></span><br>
                                                            <?php print date('M Y'); ?>

                                                        </div>
                                                        <div class="notice-details col-xs-8 col-sm-10 col-md-10">
                                                            <h5 class="title-color caption-subject  bold"><?php echo ($calendarType == 'N') ? ' कुनै सूचना फेला परेन' : 'No notice found' ?></h5>
                                                            <p><?php echo ($calendarType == 'N') ? ' नयाँ सूचना प्रकाशित हुँदा सूचना प्रदर्शन हुनेछ' : 'Notice will be display when new notice is published' ?></p>
                                                        </div>
                                                    </li>
                                                <?php endif; ?>
                                            </ul>
                                        </div>
                                        <!--END TABS-->
                                    </div>
                                </div>
                            </div>
                            <!-- END PORTLET -->
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div id="lobilist">

                </div>

            </div>

        </div>

        <!--new edit starts here-->
        <div class="col-md-12 holidays">
            <!-- BEGIN PORTLET -->
            <div class="portlet light boxborder">
                <div class="portlet-title tabbable-line">
                    <div class="caption caption-md">
                        <i class="fa fa-sign-out font-green-sharp" aria-hidden="true"></i>
                        <span class="caption-subject font-green-sharp bold"><?php echo ($calendarType == 'N') ? 'आज बिदामा रहेका कर्मचारीहरू' : 'Employee on Leave Today' ?></span>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="upcomingholidays">
                            <div class="html-loading" style="display:none;height:100%;width:100%;position:absolute;top:0;left:0;"></div>
                            <ul class="feeds" style="visibility:visible;">
                                <?php foreach ($leaveEmpToday as $details) { ?>
                                    <li><?php // echo $details['FULL_NAME'].'('.$details['LEAVE_ENAME'].') '.' ('.$details['START_DATE'].' to '.$details['END_DATE'].')';
                                        ?>
                                        <div class="col-xs-6 col-sm-3 col-md-3 desc holiday-title">
                                            <span class="label holiday-color  "><?php print ($calendarType == 'N') ? $details['NAME_NEPALI']: $details['FULL_NAME']; ?></span>
                                        </div>
                                        <div class="col-xs-6 col-sm-3 col-md-3 remaining-days">
                                            <span class="label"><?php print $details['BRANCH_NAME']; ?></span>
                                        </div>
                                        <div class="col-xs-6 col-sm-3 col-md-3 remaining-days">
                                            <span class="label"><?php print $details['LEAVE_ENAME']; ?></span>
                                        </div>
                                        <div class="col-xs-6 col-sm-3 col-md-3 holiday-date">
                                            <div class="label date"><?php print $details['START_DATE'] . ' TO ' . $details['END_DATE'] ?></div>
                                        </div>
                                    </li>
                                <?php } ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-12 holidays">
            <!-- BEGIN PORTLET -->
            <div class="portlet light boxborder">
                <div class="portlet-title tabbable-line">
                    <div class="caption caption-md">
                        <i class="fa fa-plane font-green-sharp" aria-hidden="true"></i>
                        <span class="caption-subject font-green-sharp bold"><?php echo ($calendarType == 'N') ? 'आज यात्रामा रहेका कर्मचारीहरू' : 'Employee on Travel Today' ?> </span>
                    </div>
                </div>

                <div class="portlet-body">
                    <div class="row">
                        <div class="upcomingholidays">
                            <div class="html-loading" style="display:none;height:100%;width:100%;position:absolute;top:0;left:0;"></div>
                            <ul class="feeds" style="visibility:visible;">
                                <?php foreach ($travelEmpToday as $details) { ?>
                                    <li><?php // echo $details['FULL_NAME'].'('.$details['LEAVE_ENAME'].') '.' ('.$details['START_DATE'].' to '.$details['END_DATE'].')';
                                        ?>
                                        <div class="col-xs-6 col-sm-3 col-md-3 desc holiday-title">
                                            <span class="label holiday-color  "><?php print ($calendarType == 'N') ? $details['NAME_NEPALI']: $details['FULL_NAME'] ; ?></span>
                                        </div>
                                        <div class="col-xs-6 col-sm-3 col-md-3 remaining-days">
                                            <span class="label"><?php print $details['BRANCH_NAME']; ?></span>
                                        </div>
                                        <div class="col-xs-6 col-sm-3 col-md-3 remaining-days">
                                            <span class="label"><?php print $details['DESTINATION']; ?></span>
                                        </div>
                                        <div class="col-xs-6 col-sm-3 col-md-3 holiday-date">
                                            <div class="label date "><?php print $details['FROM_DATE'] . ' TO ' . $details['TO_DATE'] ?></div>
                                        </div>
                                    </li>
                                <?php } ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <!--new edit end here-->



    </div>

    <div class="col-md-6">
        <div class="row">
            <div class="col-md-12 holidays">
                <!-- BEGIN PORTLET -->
                <div class="portlet light boxborder">
                    <div class="portlet-title tabbable-line">
                        <div class="caption caption-md">
                            <i class="fa fa-bell font-green-sharp" aria-hidden="true"></i>
                            <span class="caption-subject font-green-sharp bold"> <?php echo ($calendarType == 'N') ? 'आगामी बिदाहरू' : 'Upcoming Holidays ' ?></span>
                        </div>
                    </div>

                    <div class="portlet-body">
                        <div class="row">
                            <div class="upcomingholidays">
                                <div class="html-loading" style="display:none;height:100%;width:100%;position:absolute;top:0;left:0;"></div>
                                <ul class="feeds" style="visibility:visible;">
                                    <?php foreach ($upcomingHolidays as $holiday) : ?>
                                        <li>
                                            <div class="col-xs-6 col-sm-3 col-md-3 desc holiday-title">
                                                <span class="label holiday-color  "><?php print $holiday['HOLIDAY_ENAME']; ?></span>
                                            </div>
                                            <div class="col-xs-6 col-sm-4 col-md-4 remaining-days">
                                                <?php
                                                $daysRemaining = $holiday['DAYS_REMAINING'] ? ((1 == $holiday['DAYS_REMAINING']) ? "1 Day Remaining" : $holiday['DAYS_REMAINING'] . " Days Remaining") : "Today";
                                                ?>
                                                <span class="label"><?php print $daysRemaining; ?></span>
                                            </div>
                                            <div class="col-xs-6 col-sm-5 col-md-5 holiday-date">
                                                <div class="label date"><?php print $holiday['START_DATE']; ?></div>
                                            </div>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="birthday-wishes">
                <div class="col-md-12 col-sm-12">
                    <?php
                    // Display Today's Birthday As Active
                    $todayBirthdayActive = ((isset($employeesBirthday) && isset($employeesBirthday['TODAY']) && $employeesBirthday['TODAY'])) ? true : false;
                    ?>
                    <!-- BEGIN PORTLET-->
                    <div class="portlet light boxborder">
                        <div class="portlet-title tabbable-line tabline">
                            <div class="caption">
                                <i class="fa fa-birthday-cake font-green-sharp"></i>
                                <span class="caption-subject font-green-sharp bold"> <?php echo ($calendarType == 'N') ? 'जन्मदिनको शुभकामनाहरू' : 'Birthday Wishes' ?></span>
                            </div>
                            <ul class="nav nav-tabs">
                                <li class="ln-birthday <?php print $todayBirthdayActive ? 'active' : ''  ?>">
                                    <a id="ln-birthday-today" class="ln-nav-tab-birthday" href="javascript:void(0);" data-toggle="tab" aria-expanded="true"> <?php echo ($calendarType == 'N') ? 'आज' : 'Today' ?></a>
                                </li>
                                <li class="ln-birthday <?php print $todayBirthdayActive ? '' : 'active'  ?>">
                                    <a id="ln-birthday-upcoming" class="ln-nav-tab-birthday" href="javascript:void(0);" data-toggle="tab" aria-expanded="false"> <?php echo ($calendarType == 'N') ? 'आगामी' : 'Upcoming' ?></a>
                                </li>
                            </ul>
                        </div>

                        <div class="row">
                            <div class="tab-content birday-person-list">
                                <div class="tab-pane tab-pane-birthday">
                                    <div id="tab-birthday-today" style="display:<?php print $todayBirthdayActive ? 'block' : 'none'  ?>">
                                        <?php if ($todayBirthdayActive) : ?>
                                            <?php foreach ($employeesBirthday['TODAY'] as $todayBirthday) : ?>
                                                <div class="person-list clearfix">
                                                    <div class="col-xs-4 col-md-3 col-sm-3">
                                                        <div class="person-pic">
                                                            <img class="lazy" data-original="<?php print $todayBirthday['FILE_PATH'] ? $this->basePath('uploads/' . $todayBirthday['FILE_PATH']) : $this->basePath('img/nobody_m.original.jpg'); ?>" alt="person picture">
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-6 col-md-6 col-sm-6">
                                                        <div class="person-details">
                                                            <h4><?php print ($calendarType == 'N') ? $todayBirthday['NAME_NEPALI']: $todayBirthday['FULL_NAME'] ?> </h4>
                                                            <span><?php print $todayBirthday['DESIGNATION_TITLE']; ?></span>
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-2 col-md-3 col-sm-3">
                                                        <span class="birth-date">
                                                            <?php print $todayBirthday['EMP_BIRTH_DATE']; ?>
                                                            <a href="<?php print $this->url('birthday', ['action' => 'wish', 'id' => $todayBirthday['EMPLOYEE_ID']]); ?>" class="btn btn-link pull-right">wish</a>
                                                        </span>
                                                    </div>
                                                </div>
                                            <?php endforeach; ?>
                                        <?php else : ?>
                                            <div class="dashborder clearfix">
                                                <div class="col-xs-4 col-md-3 col-sm-3">
                                                    <div class="person-pic birthday-pic">
                                                        <img src="<?php print $this->basePath('img/nobody_m.original.jpg'); ?>" alt="person picture">
                                                    </div>
                                                </div>
                                                <div class="col-xs-6 col-md-6 col-sm-6">
                                                    <div class="nobirthday-text">
                                                        <h4><?php echo ($calendarType == 'N') ? 'आज कुनै जन्मदिन उपलब्ध छैन।' : 'No Birthday Available Today ' ?></h4>
                                                    </div>
                                                </div>
                                                <div class="col-xs-2 col-md-3 col-sm-3">
                                                    <span class="calendar_date"><i class="fa fa-calendar" aria-hidden="true"></i>&nbsp;<?php print date('jS F') ?></span>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>

                                    <div id="tab-birthday-upcoming" style="display:<?php print $todayBirthdayActive ? 'none' : 'block'  ?>">
                                        <?php if (isset($employeesBirthday) && isset($employeesBirthday['UPCOMING']) && $employeesBirthday['UPCOMING']) : ?>
                                            <?php foreach ($employeesBirthday['UPCOMING'] as $upcomingBirthday) : ?>
                                                <div class="person-list clearfix">
                                                    <div class="col-xs-4 col-md-3 col-sm-3">
                                                        <div class="person-pic">
                                                            <img class="lazy" data-original="<?php print $upcomingBirthday['FILE_PATH'] ? $this->basePath('uploads/' . $upcomingBirthday['FILE_PATH']) : $this->basePath('img/nobody_m.original.jpg'); ?>" alt="person picture">
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-6 col-md-6 col-sm-6">
                                                        <div class="person-details">
                                                            <h4><?php print ($calendarType == 'N') ? $upcomingBirthday['NAME_NEPALI']: $upcomingBirthday['FULL_NAME']; ?></h4>
                                                            <span><?php print $upcomingBirthday['DESIGNATION_TITLE']; ?></span>
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-2 col-md-3 col-sm-3">
                                                        <span class="birth-date"><?php print $upcomingBirthday['EMP_BIRTH_DATE']; ?></span>
                                                    </div>
                                                </div>
                                            <?php endforeach; ?>
                                        <?php else : ?>
                                            <div class="dashborder clearfix">
                                                <div class="col-md-3 col-sm-3">
                                                    <div class="person-pic birthday-pic">
                                                        <img src="<?php print $this->basePath('img/nobody_m.original.jpg'); ?>" alt="person picture">
                                                    </div>
                                                </div>
                                                <div class="col-xs-6 col-md-6 col-sm-6">
                                                    <div class="nobirthday-text">
                                                        <h4> <?php echo ($calendarType == 'N') ? 'आगामी जन्मदिनहरू फेला परेन!!!' : 'No Upcoming Birthdays Found!!!' ?> </h4>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered">
                    <div class="portlet-title tabbable-line">
                        <div class="caption">
                            <i class="icon-bubble font-dark hide"></i>
                            <span class="caption-subject font-hide bold uppercase"> <?php echo ($calendarType == 'N') ? 'कर्मचारीहरू' : 'Employees' ?></span>
                        </div>
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a href="#portlet_hired_this_month" data-toggle="tab"> <?php echo ($calendarType == 'N') ? 'यस महिनामा नियुक्त गरिएका' : 'Hired this month ' ?> </a>
                            </li>
                            <li>
                                <a href="#portlet_left_this_month" data-toggle="tab"> <?php echo ($calendarType == 'N') ? 'यस महिनामा छोडिएका।' : 'Left this month' ?> </a>
                            </li>
                        </ul>
                    </div>
                    <div class="portlet-body">
                        <div class="tab-content scroller" style="height:305px">
                            <div class="tab-pane active" id="portlet_hired_this_month">
                                <div class="row">
                                    <?php if (isset($newEmployees)) : ?>
                                        <?php foreach ($newEmployees as $emp) : ?>
                                            <div class="col-md-4">
                                                <!--begin: widget 1-1 -->
                                                <div class="mt-widget-1">
                                                    <div class="mt-icon">
                                                        <a href="#">
                                                            <i class="icon-plus"></i>
                                                        </a>
                                                    </div>
                                                    <div class="mt-img">
                                                        <img height="80" width="80" src="<?php print $emp['FILE_PATH'] ? $this->basePath('uploads/' . $emp['FILE_PATH']) : $this->basePath('img/nobody_m.original.jpg'); ?>">
                                                    </div>
                                                    <div class="mt-body">
                                                        <h3 class="mt-username"><?php print ($calendarType == 'N') ? $emp['NAME_NEPALI']: $emp['FULL_NAME']; ?></h3>
                                                        <p class="mt-user-title"><?php print $emp['DESIGNATION_TITLE']; ?> </p>
                                                        <div class="mt-stats">
                                                            <div class="btn-group btn-group btn-group-justified">
                                                                <a href="javascript:;" class="btn font-green">
                                                                    <i class="fa fa-plus"></i> <?php print $emp['JOIN_DATE']; ?> </a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <!--end: widget 1-1 -->
                                            </div>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div class="tab-pane" id="portlet_left_this_month">
                                <div class="row">
                                    <?php if (isset($leftEmployees)) : ?>
                                        <?php foreach ($leftEmployees as $emp) : ?>
                                            <div class="col-md-4">
                                                <!--begin: widget 1-1 -->
                                                <div class="mt-widget-1">
                                                    <div class="mt-icon">
                                                        <a href="#">
                                                            <i class="fa fa-minus-circle font-red"></i>
                                                        </a>
                                                    </div>
                                                    <div class="mt-img">
                                                        <img height="80" width="80" src="<?php print $emp['FILE_PATH'] ? $this->basePath('uploads/' . $emp['FILE_PATH']) : $this->basePath('img/nobody_m.original.jpg'); ?>">
                                                    </div>
                                                    <div class="mt-body">
                                                        <h3 class="mt-username"><?php print print ($calendarType == 'N') ? $emp['NAME_NEPALI']: $emp['FULL_NAME'] ; ?></h3>
                                                        <p class="mt-user-title"><?php print $emp['DESIGNATION_TITLE']; ?> </p>
                                                        <div class="mt-stats">
                                                            <div class="btn-group btn-group btn-group-justified">
                                                                <!--                                                                <a href="javascript:;" class="btn font-green">
                                                                                                                                    <i class="fa fa-plus"></i> <?php print $emp['JOIN_DATE']; ?> </a>-->
                                                                <a href="javascript:;" class="btn font-red">
                                                                    <i class="fa fa-minus"></i> <?php print $emp['EXIT_DATE']; ?> </a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <!--end: widget 1-1 -->
                                            </div>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="clearfix"></div>

</div>