<?php
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()->appendFile($this->basePath('js/payroll/payroll-ctc/index.js'));

$this->headScript()
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
?>




<?php if ($this->messages) { ?>
    <script>
        document.messages = <?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.wsValidateGoal = '<?= $this->url("payroll-ctc", ["action" => "validateGoal"]) ?>';
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\payroll-ctc')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <h3>Employee CTC</h3>
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">

                <div class="row">
                    <div class="col-sm-3">
                        <label>Fiscal Year</label>
                        <select class="form-control" name="fiscalYear" id="fiscalYear">
                            <option value="">Select Fiscal Year</option>
                            <?php foreach ($fiscalYears as $key => $value) { ?>
                                <option value="<?php echo $value['id'] ?>" <?php echo ($value['id']==$selectedFiscalYearId?'selected':'') ?>><?php echo $value['name'] ?></option>
                            <?php } ?>
                        </select>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <label>Employee</label>
                            <select name="employeeId" id="employeeId" class="form-control" required>
                                <option value="" disabled="" selected="">Please Select Employee</option>
                                <?php foreach ($employees as $key => $value) { ?>
                                    <option value="<?php echo $value['id'] ?>"><?php echo $value['name'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>

                    <div class="col-sm-5">
                        <button id="search" class="btn btn-default btn-sm pull-right" style="margin-top: 15px;">
                            Search
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>

                <div class="row">
                    <h3>Payroll CTC Of <span style="font-weight: bold;" id="employeeName"></span> For Fiscal Year <span style="font-weight: bold;" id="fiscalYearName"></span></h3>
                    <!-- Button for Exporting to Excel -->
                    <button id="exportExcel" class="btn btn-success" style="padding: 8px 14px 7px !important; margin-top: 5px; margin-bottom: 10px;"><i class="fa fa-file-excel-o"></i> Export to Excel</button>

                    <!-- Button for Exporting to PDF -->
                    <button id="exportPdf" class="btn btn-danger" style="padding: 8px 14px 7px !important; margin-top: 5px; margin-bottom: 10px;"><i class="fa fa-file-pdf-o"></i> Export to PDF</button>
                    <table class="table table-bordered table-striped" id="salary-table">
                        <thead>
                            <tr>
                                <th style="font-weight: bold; font-size: 16px;">Addition</th>
                                <th style="font-weight: bold; font-size: 16px;">Amount</th>
                                <th style="font-weight: bold; font-size: 16px;">Deduction</th>
                                <th style="font-weight: bold; font-size: 16px;">Amount</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>

            </div>

        </div>
    </div>
</div>

<!-- Add SheetJS (for Excel export) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.17.0/xlsx.full.min.js"></script>

<!-- Add jsPDF (for PDF export) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.js"></script>