<?php
$this->headScript()->appendFile($this->basePath('js/setup/letter/add.js'));
$this->headScript()
    ->appendFile($this->basePath('assets/global/plugins/bootstrap-summernote/summernote.min.js'));
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/bootstrap-summernote/summernote.css'));
?>

<?php
// $description = $form->get('description');
$letterTitle = $form->get('letterTitle');
$nepaliText = $form->get('nepaliText');

$submit = $form->get('submit');

$form->setAttribute('action', $this->url('letterSetup', ['action' => 'addSub', 'id' => $id]));

$form->prepare();
?>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\letterSetup')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<script>
    document.searchurl = '<?= $this->url("letterSetup", ["action" => "search"]) ?>';
</script>

<style>
    .letter-head {
        position: relative;
        width: 210mm;
        height: 297mm;
        margin: 0;
        color: #000000;
    }

    .table-bordered {
        border: 1px solid #e73d4a;
    }

    .letter-head img {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }

    .letter-content {
        position: absolute;
        top: 50mm;
        left: 10mm;
        right: 10mm;
        bottom: 10mm;
        padding: 15px;
        box-sizing: border-box;

    }

    .switch {
        position: relative;
        display: inline-block;
        width: 61px;
        height: 46px;
    }

    .switch input {
        opacity: 0;
        width: 0;
        height: 0;
    }

    .slider {
        position: absolute;
        cursor: pointer;
        top: -12px;
        left: 0;
        right: 0;
        bottom: 13px;
        background-color: #ccc;
        transition: 0.4s;
    }

    .slider:before {
        position: absolute;
        content: "";
        height: 13px;
        width: 15px;
        left: 4px;
        bottom: 4px;
        background-color: white;
        transition: 0.4s;
    }

    input:checked+.slider {
        background-color: #2196F3;
    }

    input:checked+.slider:before {
        transform: translateX(26px);
    }

    /* Rounded slider */
    .slider.round {
        border-radius: 34px;
    }

    .slider.round:before {
        border-radius: 50%;
    }

    /* Initially hide the inputs */
    .custom-style-inputs {
        display: none;
    }

    .input-container {
        display: flex;
        align-items: center;
        color: #FFFFFF;
        background-color: #2196F3;
    }

    .input-container button {
        border: none;
        background: none;
        cursor: pointer;
        padding: 0.5rem;
        font-size: 1.25rem;
        border-radius: 0;
    }

    .input-container input {
        text-align: center;
        height: 2.5rem;
    }

    .input-container .btn {
        border-radius: 0;
    }

    .keyboard-img {
        margin-left: 13px;
        width: 1037px;
        height: 307px;

    }

    .page-number {
        position: absolute;
        bottom: 77px;
        /* Adjust as necessary */
        left: 93%;
        transform: translateX(-50%);
        z-index: 999;
        text-align: right;
    }

    .note-editable {
        color: #000000 !important;
        /* Dark black text */
    }

    /* Additional styling for placeholder text */
    .note-placeholder {
        color: #000000 !important;
        /* Dark black placeholder */
    }

    /* Style for other elements like links, headings, etc. */
    .note-editable h1,
    .note-editable h2,
    .note-editable h3,
    .note-editable h4,
    .note-editable h5,
    .note-editable h6,
    .note-editable a {
        color: #000000 !important;
        /* Dark black text */
    }

    /* Style for bold, italic, underline, etc. */
    .note-editable b,
    .note-editable strong,
    .note-editable i,
    .note-editable em,
    .note-editable u {
        color: #000000 !important;
        /* Dark black text */
    }

    /* Style for table borders */
    .note-editable table,
    .note-editable th,
    .note-editable td {
        border: 1px solid #000000 !important;
        /* Dark black borders */
    }
</style>

<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <!-- <input type="text" name="parent_id" value="2"> -->
            <div class="portlet-body">
                <?= $this->form()->openTag($form); ?>
                <div class="row">
                    <div class="col-sm-3">
                        <label class="switch">
                            <input type="checkbox" id="nepaliType">
                            <span class="slider round"></span>
                        </label>
                        <span id="calendar-label" class="mt-3">Nepali Type</span>
                    </div>

                    <div class="col-xs-12 col-sm-6 col-md-12 col-lg-12 mt-5">
                        <div class="row clearfix e-setup">
                            <div class="col-md-12 colsm-12 col-xs-12">
                                <?php print $this->formElement($nepaliText); ?>
                                <?php print $this->formElementErrors()->render($nepaliText, ['class' => 'help-block error']); ?>
                            </div>
                            <div>
                                <img class="keyboard-img" id="keyboard" style="display: none;" src="<?= $this->basePath('img/nepali_keyboard.png'); ?>" alt="">
                            </div>
                        </div>
                        <div class="form-group">
                            <?php print $this->formLabel($letterTitle); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($letterTitle); ?>
                            <?php print $this->formElementErrors()->render($letterTitle, ['class' => 'help-block']); ?>
                            <span class="errorMsg" style="font-size:11px; color:red;"></span>
                        </div>
                    </div>
                </div>
                <div class="tabbable-line">
                    <div class="tab-content">

                    </div>
                </div>
                <div class="row" style="margin-bottom: 20px;">
                    <div class="col-sm-12">
                        <div class="row">
                            <div class="col-sm-4">
                                <label class="control-label">Variables</label>
                            </div>
                        </div>
                        <div class="row">
                            <?php foreach ($variables as $key => $variable) : ?>
                                <div class="col-sm-2" style="margin-top: 5px;">
                                    <a class="btn btn-block variables" data-variable="<?= $key ?>"  style="font-size: 0.9rem;"><?= $key ?></a>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <label class="switch">
                            <input type="checkbox" name="is_custom" id="CustomStyle">
                            <span class="slider round"></span>
                        </label>
                        <span id="calendar-label" class="mt-3">Custom Style</span>
                    </div>
                    <div id="custom-style-inputs" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 bg-secondary custom-style-inputs">
                        <div class="form-group col-xs-3 col-sm-3 col-md-3 col-lg-2">
                            <label for="top">Top:</label>
                            <div class="input-group input-container">
                                <div class="input-group-prepend">
                                    <button class="btn btn-outline-secondary btn-xs" type="button" data-target="top" data-delta="-1">-</button>
                                </div>
                                <input type="number" class="form-control" name="top" id="top" value="" placeholder="Value in mm" />
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary btn-xs" type="button" data-target="top" data-delta="1">+</button>
                                </div>
                            </div>
                        </div>

                        <div class="form-group col-xs-3 col-sm-3 col-md-3 col-lg-2">
                            <label for="bottom">Bottom:</label>
                            <div class="input-group input-container">
                                <div class="input-group-prepend">
                                    <button class="btn btn-outline-secondary btn-xs" type="button" data-target="bottom" data-delta="-1">-</button>
                                </div>
                                <input type="number" class="form-control" name="bottom" id="bottom" placeholder="Value in mm" />
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary btn-xs" type="button" data-target="bottom" data-delta="1">+</button>
                                </div>
                            </div>
                        </div>

                        <div class="form-group col-xs-3 col-sm-3 col-md-3 col-lg-2">
                            <label for="left">Left:</label>
                            <div class="input-group input-container">
                                <div class="input-group-prepend">
                                    <button class="btn btn-outline-secondary btn-xs" type="button" data-target="left" data-delta="-1">-</button>
                                </div>
                                <input type="number" class="form-control" name="left" id="left" placeholder="Value in mm" />
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary btn-xs" type="button" data-target="left" data-delta="1">+</button>
                                </div>
                            </div>
                        </div>

                        <div class="form-group col-xs-3 col-sm-3 col-md-3 col-lg-2">
                            <label for="right">Right:</label>
                            <div class="input-group input-container">
                                <div class="input-group-prepend">
                                    <button class="btn btn-outline-secondary btn-xs" type="button" data-target="right" data-delta="-1">-</button>
                                </div>
                                <input type="number" class="form-control" name="right" id="right" placeholder="Value in mm" />
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary btn-xs" type="button" data-target="right" data-delta="1">+</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <button class="btn btn-primary btn-xs " style="margin-bottom: 5px;" id="addPage">Add Page</button>
                <!-- <button id="downloadPdf" class="btn btn-primary btn-xs" style="margin-bottom: 5px;">Download PDF</button> -->
                <?= $this->formSubmit($submit); ?>
                <?= $this->form()->closeTag(); ?>

            </div>
        </div>
    </div>
</div>
<?php
$imgUrl = $this->basePath('uploads/' . $company_logo);
?>
<input type="hidden" id="ImageUrl" value="<?= $imgUrl ?>">
<div id="letter-head-container">

</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.5.0-beta4/html2canvas.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js"></script>