<?php
$this->headLink()
->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));
$this->headScript()->appendFile($this->basePath('dropzone/dropzone.min.js'));
$this->headScript()->appendFile($this->basePath('js/setup/employee-setup/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'employeeSetup-form');

$employeeId = $form->get('employeeId');
$employeeCode = $form->get('employeeCode');

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('employeeSetup', ['action' => 'add']));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "add"]) ?>';
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>

            <div class="row" style="margin-bottom: 5rem;">
            <div class="col-sm-4">
                        <div class="form-group <?= empty($employeeId->getMessages()) ? "" : "error" ?> ">
                            <?php print $this->formLabel($employeeId) ?>
                            <span class="required" aria-required="true">*</span>
                            <select name="employeeId" id="employeeId" required="required" class="form-control">
                                <option value="" disabled="" selected="" class="ng-binding">Please select</option>
                                <?php foreach ($HrisEmployees as $key => $value) { ?>
                                    <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block error']); ?>
                    </div>
                    <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($employeeCode->getMessages()) ? "" : "error" ?> ">
                            <?php print $this->formLabel($employeeCode) ?>
                            <span class="required" aria-required="true">*</span>
                            <select name="employeeCode" id="employeeCode" required="required" class="form-control">
                                <option value="" disabled="" selected="" class="ng-binding">Please select</option>
                                <?php foreach ($DnmEmployees as $key => $value) { ?>
                                    <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
                                <?php } ?>
                            </select>
                        </div>

            </div>
            </div>

                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>

        </div>
    </div>
</div>
