<?php
$this->headScript()->appendFile($this->basePath('js/setup/employee-setup/edit.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'employeeSetup-form');

$employeeId = $form->get('employeeId');
$employeeCode = $form->get('employeeCode');

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('employeeSetup', ['action' => 'edit', 'id' => $id]));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "edit"]) ?>';
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
   
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>

<div class="row" style="margin-bottom: 5rem;">
    <div class="col-sm-6">
        <div class="form-group <?= empty($employeeId->getMessages()) ? "" : "has-error" ?>">
            <?php print $this->formLabel($employeeId); ?>
            <span class="required" aria-required="true">*</span>
            <select name="employeeId" class="form-control">
                <option value="">Select Employee</option>
                <?php foreach ($HrisEmployees as $key => $value) { ?>
                    <option value="<?php echo $key; ?>" <?= ($key == $employeeId->getValue()) ? 'selected' : '' ?>>
                        <?php echo $value; ?>
                    </option>
                <?php } ?>
            </select>
            <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block']); ?>
        </div>
    </div>
    
    <div class="col-sm-4">
        <div class="form-group <?= empty($employeeCode->getMessages()) ? "" : "has-error" ?>">
            <?php print $this->formLabel($employeeCode); ?>
            <select name="employeeCode" class="form-control">
                <option value="">Select Code</option>
                <?php foreach ($DnmEmployees as $key => $value) { ?>
                    <option value="<?php echo $key; ?>" <?= ($key == $employeeCode->getValue()) ? 'selected' : '' ?>>
                        <?php echo $value; ?>
                    </option>
                <?php } ?>
            </select>
            <?php print $this->formElementErrors()->render($employeeCode, ['class' => 'help-block']); ?>
        </div>
    </div>
</div>
                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>

        </div>
    </div>
</div>
